### ISSUE TITLE
IO

### ISSUE THREAD

**Issue by geekingfrog** [c-cube/IKSML#2]
How can I perform IO in IKSML?
I'd like to dynamically retrieve some computation from mongoDB before posting the result on my enterprise twitter feed, but I haven't found anything in your example to do that.
Great initiative otherwise.

**Comment by c-cube** [comment]
To perform IO, just return the [Church encoding](https://en.wikipedia.org/wiki/Church_encoding) of the string you want to output. For binding to mongoDB, since it is based not on XML but on bson, which is not IKSML-compliant nor entreprisey, more work is needed; get in touch with my SSII and we'll propose you a very competitive price to implement the feature (99$ hourly billing)! Remember that XML is more webscale.
